###########
# site.url, site.title

title: 'Trend Micro Bot Sample Title'

## note: 
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
path: /trend-bot
url:  '/trend-bot'


########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style: expanded 

baseurl: /trend-bot
exclude: ['README.md']

port: 4000
encoding: utf-8